#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "python"
    style = "powerline"
    powerline_symbol = ""
    foreground = "yellow"
    background = "transparent"
    template = "{{ if .Venv }} {{ .Venv }} {{ end }}"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
        style = 'full'
  
  [[blocks.segments]]
    type = "git"
    style = 'plain'
    foreground = '#6c6c6c'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed)}}*{{ end }}'

    [blocks.segments.properties]
        fetch_status = true

[[blocks]]
    type = 'rprompt'
    overflow = 'hidden'

    [[blocks.segments]]
        type = 'executiontime'
        style = 'plain'
        foreground = 'yellow'
        background = 'transparent'
        template = '{{ .FormattedMs }}'

        [blocks.segments.properties]
            threshold = 5000
            style = 'austin'
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
        "{{if gt .Code 0}}red{{end}}",
        "{{if eq .Code 0}}magenta{end}}",
    ]
    foreground = 'magenta'
    background = 'transparent'
    template = "❯"

[transient_prompt]
    foreground = "magenta"
    foreground_templates = [
        "{{if gt .Code 0}}red{{end}}",
        "{{if eq .Code 0}}magenta{end}}",
    ]
    background = "transparent"
    template = "❯ "
