#!/bin/zsh
SOURCE="$HOME/classes"
DEST="remote:class_notes"


rclone sync --update --verbose --transfers 30 --checkers 8 \
  --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 \
  --stats 30s --exclude-from "$EXCLUDE_FILE" \
  --delete-excluded "$SOURCE" "$DEST
